keys:
  - &vincenzo age16k06xjvtqk9ejwvzqvtq2u78kp4dvxsqpp62mtc9y2ggujpqg3cswf8shm
  - &dmbs_server 64ecdbc882cef53555ac468ae609f1ed2df8a933
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
        - *vincenzo
